### ISSUE TITLE
Stream Output not send via Slack if pipelines are set and not rules

### ISSUE THREAD

**Issue by mickaelReuze** [Graylog2/documentation#470]
Hello guys,

I'm using pipelines to filter a huge log and return it to a stream.
This stream is supposed send the log via a webhook on Slack but doesn't work.

**To be more clear:**
I have 2 streams, first is `message` and second is `hook`
I created a pipeline which filter log from `message` and send the result to `hook`. (It's working as expected)

Then I added an output to `hook` to send the log via Slack using a webhook.
This is not working.

If I add a rule to `hook` I will receive the log.

* Graylog Version: 2.4.4
* Elasticsearch Version: 5.6.9
* MongoDB Version: db version v2.6.12
* Operating System: Centos 7 4.9.87
* Browser version: Chrome 68.0.3440.106

**Comment by jalogisch** [comment]
Dude, this is the repository and issue tracker for the documentation not the Graylog server. 

You might want to re-open your issue in the Server repo: https://github.com/Graylog2/graylog2-server/issues

BUT you should be a little more verbose how this can be reproduced. Did you test if this is not just a bug in the slack plugin that you might use? 

I'll close this issue here as this is the complete wrong place. Maybe the community support will help you first better.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
